branches:
  only:
  - master
  - /^it\/.*$/
language: groovy
jdk:
  - openjdk8
sudo: required
services:
  - docker
env:
  global:
    MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
cache:
  directories:
  - $HOME/.m2

# Travis Lifecycle: https://docs.travis-ci.com/user/job-lifecycle#the-job-lifecycle
# Travis Stages: https://docs.travis-ci.com/user/build-stages/
# Travis Conditions: https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# Travis GHPages deploy provider: https://docs.travis-ci.com/user/deployment/pages/
jobs:
  include:
    - stage: Tests
      name: Unit Tests
      before_script:
        - echo hello1
      script:
        - echo hello2
      after_script:
        - echo hello3
    - name: Consumer Tests
      script: cd consumer-test && groovy consumerTestController.groovy

    - stage: Docs
      name: Create Documentation
      install: docker pull squidfunk/mkdocs-material:3.0.4
      before_script: documentation/bin/createDocu.sh
      script:
        - docker run -u `id -u`:`id -g` --rm -it -v ${TRAVIS_BUILD_DIR}/documentation:/docs squidfunk/mkdocs-material:3.0.4 build --clean --strict
        - mkdir -p documentation/docs-gen/misc
        - cp target/docuMetaData.json documentation/docs-gen/misc
      deploy:
        on:
          branch: master
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        name: 'Travis CI Publisher'
        local_dir: 'documentation/docs-gen'
        keep_history: true
        #verbose: true
